//   SSH:2211321,
//   FirstName: "ali",
//   MidName: "saber",
//   LastName: "Mahmoud",
//   SocialStatus: "orphans",
//   Sector: "special",
//   ApprovalStatus: "no",
//   Phone: "77777777777",
//   CashBenefits: 11,
//   Box:3,
//   CheckDate: "2023-07-23",
//   StartDate: "2023-07-23",
//   Birthdate: "2023-07-23",
//   Description: "mamama",
//   Town: "gaga",
//   Street: "lsdkfj",
//   MonthlyIncome: 111,
//   MonthlyOutcome:1112,
//   File: Joi.when("ApprovalStatus", {
//     is: "yes",
//     then: fileSchema.required(),
//     otherwise: fileSchema.optional(),
//   }),
//   Dependent: [{"name":"teto",age:4,gender:"male",disabled:false,study:true,description:"good boy",birthdate:""2023-01-11""}],
//   Researcher: "no one",
//   ResearchOpinion: "no opinoinnnn",
// }
