const Joi = require("joi");

const BaseCaseSchemaValidation = Joi.object({
  ssh: Joi.number().required(),
  firstname: Joi.string().trim().required(),
  midname: Joi.string().trim().required(),
  lastname: Joi.string().trim().required(),
  status: Joi.string().valid("poor", "widows", "orphans").required(),
  phone: Joi.string().length(11).required(),
  deserve: Joi.string().valid("yes").required(),
  salary: Joi.number().required(),
  box: Joi.number().default(1),
  checkDate: Joi.date().required(),
  startDate: Joi.date().required(),
  birthdate: Joi.date().required(),
  description: Joi.string().required(),
  town: Joi.string().trim().required(),
  street: Joi.string().trim().required(),
  monthlyIncome: Joi.number().required(),
  monthlyOutcome: Joi.number().required(),
  sponsor: Joi.string().valid("foundation").required(),
  document: Joi.array().items(Joi.string()).required(),
  dependent: Joi.array().items(Joi.string()),
  researchOpinions: Joi.array().items(Joi.string()).required(),
});

const specialCaseShema = Joi.object({
  ssh: Joi.number().required(),
  firstname: Joi.string().trim().required(),
  midname: Joi.string().trim().required(),
  lastname: Joi.string().trim().required(),
  salary: Joi.number().required(),
  box: Joi.number().default(1).required(),
  sponsor: Joi.string().valid("special").required(),
  deserve: Joi.string().valid("yes", "no").required(),
  description: Joi.string(),
  phone: Joi.number(),
  status: Joi.string().trim().valid("poor", "widows", "orphans"),
  town: Joi.string().trim(),
  street: Joi.string().trim(),
  monthlyIncome: Joi.number(),
  monthlyOutcome: Joi.number(),
  checkDate: Joi.date(),
  startDate: Joi.date(),
  birthdate: Joi.date(),
  document: Joi.array().items(Joi.string()),
  researchOpinions: Joi.array().items(Joi.string()),
});

const watingCaseShema = Joi.object({
  ssh: Joi.number().required(),
  firstname: Joi.string().trim().required(),
  midname: Joi.string().trim().required(),
  lastname: Joi.string().trim().required(),
  description: Joi.string().required(),
  status: Joi.string().valid("poor", "widows", "orphans").required(),
  deserve: Joi.string().valid("wating").required(),
  town: Joi.string().trim().required(),
  street: Joi.string().trim().required(),
  phone: Joi.number().required,
  monthlyIncome: Joi.number(),
  monthlyOutcome: Joi.number(),
  box: Joi.number(),
  birthdate: Joi.date(),
});

const notDeserveCaseShema = Joi.object({
  ssh: Joi.number().required(),
  firstname: Joi.string().trim().required(),
  midname: Joi.string().trim().required(),
  lastname: Joi.string().trim().required(),
  phone: Joi.string().length(11),
  description: Joi.string().required(),
  status: Joi.string().valid("poor", "widows", "orphans").required(),
  sponsor: Joi.string().valid("foundation").required(),
  deserve: Joi.string().valid("no").required(),
  town: Joi.string().trim().required(),
  street: Joi.string().trim(),
  monthlyIncome: Joi.number(),
  monthlyOutcome: Joi.number(),
  salary: Joi.number(),
  box: Joi.number(),
  checkDate: Joi.date(),
  startDate: Joi.date(),
  birthdate: Joi.date(),
});

const factoryCaseShema = Joi.object({
  ssh: Joi.number().required(),
  firstname: Joi.string().trim().required(),
  midname: Joi.string().trim().required(),
  lastname: Joi.string().trim().required(),
  description: Joi.string().required(),
  phone: Joi.string().length(11).required(),
  status: Joi.string().valid("poor", "widows", "orphans").required(),
  deserve: Joi.string().valid("yes").required(),
  sponsor: Joi.string().valid("factory").required(),
  town: Joi.string().trim().required(),
  street: Joi.string().trim().required(),
  monthlyIncome: Joi.number().required(),
  monthlyOutcome: Joi.number().required(),
  salary: Joi.number().required(),
  box: Joi.number().default(1),
  checkDate: Joi.date().required(),
  startDate: Joi.date().required(),
  birthdate: Joi.date().required(),
  document: Joi.array().items(Joi.string()).required(),
  dependent: Joi.array().items(Joi.string()),
  researchOpinions: Joi.array().items(Joi.string()),
});

module.exports = {
  BaseCaseSchemaValidation,
  specialCaseShema,
  watingCaseShema,
  notDeserveCaseShema,
  factoryCaseShema,
};
